"""initial schema: tenant, identity, role, role_assignment, audit_event

Revision ID: 27e0333fad26
Revises: 
Create Date: 2026-08-21 00:32:39.410503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e0333fad26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_identity_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_event_hash', sa.Text(), nullable=True),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_number')
    )
    op.create_table('identity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_subject', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('service_client_id', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'external_subject', name='uq_identity_issuer_subject'),
    sa.UniqueConstraint('service_client_id')
    )
    op.create_table('role_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_role_assignment_active', 'role_assignment', ['identity_id', 'role_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_role_assignment_active', table_name='role_assignment', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('role_assignment')
    op.drop_table('identity')
    op.drop_table('audit_event')
    op.drop_table('tenant')
    op.drop_table('role')
    # ### end Alembic commands ###
