"""model registry: model, model_version, model_runtime_state

Revision ID: 63f684d35463
Revises: d4fe470591dd
Create Date: 2026-08-21 00:52:16.673485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f684d35463'
down_revision: Union[str, None] = 'd4fe470591dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('declared_source', sa.Text(), nullable=True),
    sa.Column('declared_license', sa.Text(), nullable=True),
    sa.Column('base_model_version_id', sa.UUID(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('risk_classification', sa.Text(), nullable=True),
    sa.Column('malware_scan_result', sa.Text(), nullable=False),
    sa.Column('malware_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_verified_at_import', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['imported_by'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runtime_state',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('runtime_status', sa.Text(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hash_reverify_result', sa.Text(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_runtime_state')
    op.drop_table('model_version')
    op.drop_table('model')
    # ### end Alembic commands ###
