"""governance: application, risk questionnaire, permitted roles, governance approvals; evaluation_run forward-declaration

Revision ID: e91da829bbe5
Revises: 63f684d35463
Create Date: 2026-08-21 01:05:18.251948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e91da829bbe5'
down_revision: Union[str, None] = '63f684d35463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('permitted_data', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('restricted_data', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('autonomous_action_allowed', sa.Boolean(), nullable=False),
    sa.Column('external_network_allowed', sa.Boolean(), nullable=False),
    sa.Column('risk_classification', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_permitted_role',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'role_id')
    )
    op.create_table('governance_approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence_evaluation_run_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['evidence_evaluation_run_id'], ['evaluation_run.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_questionnaire_response',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('processes_phi', sa.Boolean(), nullable=False),
    sa.Column('analyzes_medical_images', sa.Boolean(), nullable=False),
    sa.Column('analyzes_physiological_signals', sa.Boolean(), nullable=False),
    sa.Column('generates_patient_specific_recommendations', sa.Boolean(), nullable=False),
    sa.Column('recommends_diagnosis', sa.Boolean(), nullable=False),
    sa.Column('recommends_treatment', sa.Boolean(), nullable=False),
    sa.Column('influences_medication_decisions', sa.Boolean(), nullable=False),
    sa.Column('produces_time_critical_recommendations', sa.Boolean(), nullable=False),
    sa.Column('takes_autonomous_clinical_action', sa.Boolean(), nullable=False),
    sa.Column('allows_independent_clinician_review', sa.Boolean(), nullable=False),
    sa.Column('directly_affects_patient_care', sa.Boolean(), nullable=False),
    sa.Column('suggested_classification', sa.Text(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['identity.id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_questionnaire_response')
    op.drop_table('governance_approval')
    op.drop_table('application_permitted_role')
    op.drop_table('evaluation_run')
    op.drop_table('application')
    # ### end Alembic commands ###
