"""governance approval superseded_at

Revision ID: f8a14673e4f2
Revises: 6fce0d86705e
Create Date: 2026-08-21 23:49:26.446611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a14673e4f2'
down_revision: Union[str, None] = '6fce0d86705e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('governance_approval', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('governance_approval', 'superseded_at')
    # ### end Alembic commands ###
